server:
  port: 8080

supos:
  test:
#    url: http://47.236.10.165:30391/open-api/supos/oodm/v2/attributes/current
    url: http://192.168.2.171:30391/open-api/supos/oodm/v2/attributes/current
    sign: Sign 485a77f0613a6946d3c42f0a7307b7cd-38baef4223f2a4626238dc8ecd419b5bcdb6ef7520e0fa13e45b7b6442dae1c1
    prefix_sugar: sugarapi_sugarapi.LMS.SUGAR_AREA.sugarapi_sugarapi.
    prefix_power: sugarapi_sugarapi.LMS.POWER_AREA.sugarapi_sugarapi.
    prefix_grains: sugarapi_sugarapi.LMS.Grains_Production_Summary_On_Maize_Rice.sugarapi_sugarapi.
    prefix_distillery: sugarapi_sugarapi.LMS.DISTILLERY_AREA.sugarapi_sugarapi.
    ak: e3167b0b0eac09e13e8a91fa3119718
    sk: aefc3e2e9787b44d56197ce63b72aec9
  prod:
    url: http://47.236.10.165:30389/open-api/supos/oodm/v2/attributes/current
    prefix: sugarapi_sugarapi.CMS.CANE_MANAGEMENT_SYSTEM_SUGAR.sugarapi_sugarapi.
    ak: 9efe93223680e705d60837b743828acf
    sk: 4bae75c450750f90e7523ff580841369